// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWp6wzwhdTtSEQ-y5c5qpXRVIYLhrVW0E',
    appId: '1:212877237572:web:ac8b43f9ff8bb5bf2a0b11',
    messagingSenderId: '212877237572',
    projectId: 'curd-flutter-v2',
    authDomain: 'curd-flutter-v2.firebaseapp.com',
    databaseURL: 'https://curd-flutter-v2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'curd-flutter-v2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYq49-JjGjqBJJQnc1Wl4dEzqscPZa-kY',
    appId: '1:212877237572:android:5cb91e73e5ef06332a0b11',
    messagingSenderId: '212877237572',
    projectId: 'curd-flutter-v2',
    databaseURL: 'https://curd-flutter-v2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'curd-flutter-v2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4RyRoCFOdyB2j5MSyV4c7qwwxgWM9mrk',
    appId: '1:212877237572:ios:3dfad79faba9a9b02a0b11',
    messagingSenderId: '212877237572',
    projectId: 'curd-flutter-v2',
    databaseURL: 'https://curd-flutter-v2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'curd-flutter-v2.appspot.com',
    iosBundleId: 'com.example.curdFlutter',
  );
}
